Update build-ofox.yml

diff --git a/.github/workflows/build-ofox.yml b/.github/workflows/build-ofox.yml
--- a/.github/workflows/build-ofox.yml
+++ b/.github/workflows/build-ofox.yml
@@ -139,7 +139,13 @@ jobs:
       - name: Build OrangeFox
         run: |
           cd workspace
+          set +e
           source build/envsetup.sh
+          if [ $? -ne 0 ]; then
+            echo "ERROR: build/envsetup.sh failed"
+            ls -la
+            exit 1
+          fi
 
           export ALLOW_MISSING_DEPENDENCIES=true
           export FOX_BUILD_DEVICE=${{ inputs.DEVICE_NAME }}
@@ -161,7 +167,13 @@ jobs:
           export LC_ALL=C
 
           lunch ${{ inputs.MAKEFILE_NAME }}-eng
+          if [ $? -ne 0 ]; then
+            echo "ERROR: lunch failed"
+            exit 1
+          fi
+
           mka ${{ inputs.BUILD_TARGET }} -j$(nproc --all) 2>&1 | tee build.log
+          exit ${PIPESTATUS[0]}
 
       - name: Check build output
         run: |
